apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mistudio-explain-data
  namespace: mistudio-services
  labels:
    app: mistudio-explain
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: microk8s-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mistudio-explain-models
  namespace: mistudio-services
  labels:
    app: mistudio-explain
    component: model-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: microk8s-hostpath

