apiVersion: v1
kind: ServiceAccount
metadata:
  name: mistudio-explain
  namespace: mistudio-services
  labels:
    app: mistudio-explain
    component: security
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mistudio-explain
  namespace: mistudio-services
  labels:
    app: mistudio-explain
    component: security
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mistudio-explain
  namespace: mistudio-services
  labels:
    app: mistudio-explain
    component: security
subjects:
- kind: ServiceAccount
  name: mistudio-explain
  namespace: mistudio-services
roleRef:
  kind: Role
  name: mistudio-explain
  apiGroup: rbac.authorization.k8s.io

